main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
description: A backup plugin for instant backup creation with little to no performance impact
authors:
  - Seblii
  - onetwoeight

api-version: "1.21.1"
website: https://github.com/Levviata/ServerBackup
load: STARTUP

commands:
  backup:
    aliases: [ serverbackup ]
    permission: backup.admin

permissions:
  backup.admin:
    description: Permission for all backup commands
  backup.notification:
    description: Permission for receiving information about backups
  backup.update:
    description: Permission for receiving update messages